"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Mic2, Play, Volume2 } from "lucide-react";
import { Button, Panel } from "@/components/ui";
import { SpeechRecorder } from "@/components/speech-recorder";
import { AnswerComparisonView } from "@/components/answer-comparison";
import { ComparisonModeControl } from "@/components/comparison-mode-control";
import { SemanticComparisonProgress } from "@/components/semantic-comparison-progress";
import { useSemanticComparisonProgress } from "@/components/use-semantic-comparison-progress";
import type { AnswerComparisonMode, Evaluation } from "@/lib/types";

type Turn = { id: string; question: string; index: number };
type InterviewResult = Evaluation & { question: string; answer: string; otherQuestions: string[] };
export default function InterviewPage() {
  const [sessionId, setSessionId] = useState<string | null>(null); const [turn, setTurn] = useState<Turn | null>(null); const [total, setTotal] = useState(0); const [answer, setAnswer] = useState(""); const [scores, setScores] = useState<InterviewResult[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [comparisonMode, setComparisonMode] = useState<AnswerComparisonMode>("embedding"); const [llmConfigured, setLlmConfigured] = useState(false); const semanticProgress = useSemanticComparisonProgress();
  useEffect(() => { fetch("/api/settings").then((response) => response.json()).then((settings) => { const configured = Boolean(settings.llmConfigured); setComparisonMode(settings.answerComparisonMode === "llm" && configured ? "llm" : "embedding"); setLlmConfigured(configured); }).catch(() => undefined); }, []);
  const start = async () => { setBusy(true); setError(""); const data = await fetch("/api/interview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "start", mode: "real" }) }).then((r) => r.json()); setBusy(false); if (data.error) { setError(data.error); return; } setSessionId(data.sessionId); setTurn(data.turn); setTotal(data.total); };
  const speak = () => { if (turn && "speechSynthesis" in window) { speechSynthesis.cancel(); speechSynthesis.speak(new SpeechSynthesisUtterance(turn.question)); } };
  const submit = async () => { if (!turn || !sessionId || !answer.trim()) return; setBusy(true); const submittedAnswer = answer; const data = await semanticProgress.request<{ evaluation?: Evaluation; answeredQuestion?: string; otherQuestions?: string[]; finished?: boolean; turn?: Turn; total?: number; error?: string }>("/api/interview", { action: "answer", sessionId, turnId: turn.id, answer: submittedAnswer, comparisonMode }, comparisonMode === "embedding"); setBusy(false); if (!data.evaluation) { setError(data.error ?? "无法完成本次比对。"); return; } setScores((items) => [...items, { ...data.evaluation!, question: data.answeredQuestion ?? turn.question, answer: submittedAnswer, otherQuestions: data.otherQuestions ?? [] }]); setAnswer(""); if (data.finished) setTurn(null); else if (data.turn) { setTurn(data.turn); setTotal(data.total ?? total); } };
  if (!sessionId) return <><SemanticComparisonProgress open={semanticProgress.open} progress={semanticProgress.progress}/><header className="page-header"><div><p className="eyebrow"><Mic2 size={15}/> 模拟面试</p><h1>把答案放进真实语境。</h1><p>问题来自你的卡片；邻近追问会清晰标为 AI 拓展。</p></div></header><Panel className="interview-intro"><div className="microphone-orb"><Mic2 size={34}/></div><h2>15 分钟真实模拟</h2><p>系统会逐题提问、记录你的回答，并在结束后给出表达和知识覆盖反馈。</p><Button onClick={start} disabled={busy}><Play size={17}/> {busy ? "准备中…" : "开始模拟"}</Button>{error && <p className="danger">{error} <Link href="/cards">去创建卡片</Link></p>}</Panel></>;
  if (!turn) { const average = scores.length ? Math.round(scores.reduce((sum, item) => sum + item.score, 0) / scores.length) : 0; return <><SemanticComparisonProgress open={semanticProgress.open} progress={semanticProgress.progress}/><header className="page-header"><div><p className="eyebrow">面试报告</p><h1>这场练习完成了。</h1><p>把薄弱点带回复习队列，下一次会更稳。</p></div></header><Panel className="interview-stage"><div className="report-score">{average}</div><h2>综合表现</h2><div className="stack interview-results" style={{ marginTop: 20 }}>{scores.map((score, index) => <article className="interview-result" key={`${index}-${score.question}`}><p className="result-question">第 {index + 1} 题 · {score.question}</p><div className="feedback"><strong>{score.score} 分</strong><p>{score.feedback}</p>{score.gaps.length > 0 && <p>建议回流：{score.gaps.join("、")}</p>}</div><AnswerComparisonView comparison={score.comparison} answer={score.answer}/>{score.otherQuestions.length > 0 && <div className="more-questions compact"><p className="eyebrow">这题还可能这样问</p><ul>{score.otherQuestions.map((question) => <li key={question}>{question}</li>)}</ul></div>}</article>)}</div><div className="form-actions" style={{ marginTop: 24 }}><Button onClick={() => { setSessionId(null); setScores([]); }}>再来一次</Button></div></Panel></>;
  }
  return <><SemanticComparisonProgress open={semanticProgress.open} progress={semanticProgress.progress}/><section className="interview-stage"><p className="question-number">第 {turn.index} / {total} 题 · 真实面试模式</p><h1 className="interview-question">{turn.question}</h1><div className="form-grid"><textarea className="answer" value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="建议按要点分行作答（如 1. … 换行 2. …），识别和高亮效果最佳。" /><ComparisonModeControl mode={comparisonMode} onChange={setComparisonMode} llmConfigured={llmConfigured} compact /><p className="transcript-note">语音会转写到输入框，你可以在提交前修正措辞。</p><div className="form-actions"><Button variant="ghost" onClick={speak}><Volume2 size={17}/> 朗读问题</Button><SpeechRecorder onTranscript={(value) => setAnswer((old) => `${old}${old ? "\n" : ""}${value}`)} /><Button disabled={!answer.trim() || busy} onClick={submit}>{busy ? "正在进行本地语义比对…" : "提交这一题"}</Button></div></div></section></>;
}
