"use client";

import { useEffect, useState } from "react";
import { LoadingCard, Notice, WebShell } from "../web-shell";
import { uid, webFetch } from "../web-client";

type Card = { id: string; question: string; answer: string; answerPoints: Array<{ content?: string }> };
type Eval = { mode: "llm" | "self"; evaluationId: string; reference?: string; feedback?: string; evaluation?: { score: number; feedback: string; gaps: string[]; suggestedRating: string }; quota: { remaining: number; limit: number } };
export default function ReviewPage() {
  const [cards, setCards] = useState<Card[]>([]); const [card, setCard] = useState<Card | null>(null); const [answer, setAnswer] = useState(""); const [evaluation, setEvaluation] = useState<Eval | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(true); const [readOnly, setReadOnly] = useState(false);
  function load() { setBusy(true); webFetch<{ initial: Card[]; review: Card[]; readOnly: boolean }>("web/review/queue").then((body) => { const list = [...body.review, ...body.initial]; setCards(list); setCard(list[0] ?? null); setReadOnly(body.readOnly); }).catch((error) => setMessage(error.message)).finally(() => setBusy(false)); }
  useEffect(load, []);
  async function evaluate() { if (!card || !answer.trim()) return; setBusy(true); try { setEvaluation(await webFetch<Eval>("web/review/evaluate", { method: "POST", body: JSON.stringify({ scope: { kind: "self", cardId: card.id }, answer, operationId: uid() }) })); } catch (error) { setMessage(error instanceof Error ? error.message : "评分失败"); } finally { setBusy(false); } }
  async function confirm(rating: string) { if (!card || !evaluation) return; setBusy(true); try { await webFetch("web/review/confirm", { method: "POST", body: JSON.stringify({ evaluationId: evaluation.evaluationId, operationId: uid(), answer, rating }) }); setAnswer(""); setEvaluation(null); const next = cards.filter((item) => item.id !== card.id); setCards(next); setCard(next[0] ?? null); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setBusy(false); } }
  return <WebShell title="学习与复习" eyebrow={`${cards.length} 张待完成`}>{readOnly && <Notice kind="warn">当前处于会员到期后的只读宽限期，可以浏览卡片，但不能提交练习或保存进度。</Notice>}<section className="review-stage">{busy && !card ? <LoadingCard /> : !card ? <div className="review-empty"><b>✓</b><h2>今天完成啦</h2><p>可以去社区发现新的练习内容。</p></div> : <><div className="review-progress"><i style={{ width: `${Math.max(8, 100 / cards.length)}%` }} /></div><article className="review-card"><small>先用自己的话回答</small><h2>{card.question}</h2><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} disabled={Boolean(evaluation) || readOnly} placeholder="在这里写下你的回答…" />{!evaluation && <button className="web-primary" disabled={busy || !answer.trim() || readOnly} onClick={evaluate}>{busy ? "评分中…" : "提交回答"}</button>}{evaluation && <div className="evaluation"><div className="evaluation-score"><strong>{evaluation.evaluation?.score ?? "自评"}</strong><span>{evaluation.mode === "llm" ? `今日还可评分 ${evaluation.quota.remaining} 次` : "参考答案已显示"}</span></div><p>{evaluation.evaluation?.feedback ?? evaluation.feedback}</p>{evaluation.mode === "self" && <pre>{evaluation.reference}</pre>}<div className="rating-row"><button onClick={() => confirm("again")}>重来</button><button onClick={() => confirm("hard")}>困难</button><button onClick={() => confirm("good")}>掌握</button><button onClick={() => confirm("easy")}>轻松</button></div></div>}{message && <Notice kind="warn">{message}</Notice>}</article></>}</section><Notice>浏览器使用服务端大模型评分；额度用完时可查看参考答案并自评。桌面端支持无限次本地 BGE-M3 向量评分。</Notice></WebShell>;
}
