"use client";

import { useEffect, useState } from "react";
import { LoadingCard, Notice, WebShell } from "../web-shell";
import { uid, webFetch } from "../web-client";

type Base = { id: string; title: string; summary: string; cardCount: number; rating: number; isFree: boolean; category: string; tags: string[] };
type Card = { question?: string; answer?: string; answer_points?: Array<{ content?: string }> };
type EvaluationResult = { evaluationId: string; feedback?: string; reference?: string; evaluation?: { feedback?: string } };
export default function CommunityPage() {
  const [bases, setBases] = useState<Base[]>([]); const [base, setBase] = useState<Base | null>(null); const [card, setCard] = useState<Card | null>(null); const [position, setPosition] = useState(0); const [answer, setAnswer] = useState(""); const [result, setResult] = useState<EvaluationResult | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/community/catalog").then((r) => r.json()).then((body) => setBases(body.knowledgeBases ?? [])); }, []);
  async function open(item: Base, pos = 0) { setMessage(""); setResult(null); setAnswer(""); try { const body = await webFetch<{ card: Card }>(`community/knowledge-bases/${item.id}/cards/${pos}`); setBase(item); setPosition(pos); setCard(body.card); } catch (error) { setMessage(error instanceof Error ? error.message : "无法打开知识库"); } }
  async function evaluate() { if (!base) return; try { setResult(await webFetch<EvaluationResult>("web/review/evaluate", { method: "POST", body: JSON.stringify({ scope: { kind: "community", knowledgeBaseId: base.id, position }, answer, operationId: uid() }) })); } catch (error) { setMessage(error instanceof Error ? error.message : "评分失败"); } }
  async function confirm(rating: string) { if (!result) return; try { await webFetch("web/review/confirm", { method: "POST", body: JSON.stringify({ evaluationId: result.evaluationId, operationId: uid(), answer, rating }) }); if (base && position + 1 < base.cardCount) open(base, position + 1); else { setCard(null); setResult(null); setMessage("这套知识库的练习进度已保存。"); } } catch (error) { setMessage(error instanceof Error ? error.message : "进度保存失败"); } }
  return <WebShell title="知识社区" eyebrow="免费与已购内容">{message && <Notice kind="warn">{message}</Notice>}{card && base ? <section className="community-practice"><button className="text-back" onClick={() => setCard(null)}>← 返回社区</button><small>{base.title} · {position + 1}/{base.cardCount}</small><h2>{card.question}</h2><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} disabled={Boolean(result)} placeholder="先写下自己的回答…" />{!result ? <button className="web-primary" onClick={evaluate} disabled={!answer.trim()}>提交评分</button> : <div className="evaluation"><p>{result.evaluation?.feedback ?? result.feedback}</p>{result.reference && <pre>{result.reference}</pre>}<div className="rating-row"><button onClick={() => confirm("again")}>重来</button><button onClick={() => confirm("hard")}>困难</button><button onClick={() => confirm("good")}>掌握</button><button onClick={() => confirm("easy")}>轻松</button></div></div>}<p className="watermark">{base.id} · 账号授权内容 · 请勿传播</p></section> : <div className="community-grid">{!bases.length && <LoadingCard />}{bases.map((item) => <article key={item.id} className={`community-product ${item.isFree ? "free" : "paid"}`}><div><span>{item.category}</span><b>{item.isFree ? "免费" : "账号权益"}</b></div><h2>{item.title}</h2><p>{item.summary}</p><ul>{item.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul><footer><span>{item.cardCount} 题 · ★ {item.rating}</span><button onClick={() => open(item)}>开始练习</button></footer></article>)}</div>}</WebShell>;
}
