"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Database, Download, FileUp, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui";
import { ShareImportDialog } from "@/components/share-import-dialog";
import type { KnowledgeBase } from "@/lib/types";

export function KnowledgeBaseManager({ onChange }: { onChange?: () => void }) {
  const [bases, setBases] = useState<KnowledgeBase[]>([]); const [open, setOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editing, setEditing] = useState<KnowledgeBase | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/knowledge-bases", { cache: "no-store" }); const data = await response.json() as { knowledgeBases: KnowledgeBase[] }; setBases(data.knowledgeBases); }, []);
  useEffect(() => { void load(); }, [load]);
  const edit = (base?: KnowledgeBase) => { setEditing(base ?? null); setName(base?.name ?? ""); setDescription(base?.description ?? ""); setOpen(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const response = await fetch("/api/knowledge-bases", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(editing ? { id: editing.id } : {}), name, description }) }); const data = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setNotice(data.error ?? "无法保存知识库。"); return; } setOpen(false); setNotice("知识库已保存。"); await load(); onChange?.(); };
  const remove = async () => { if (!editing || !window.confirm(`删除知识库“${editing.name}”？`)) return; setBusy(true); const response = await fetch("/api/knowledge-bases", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing.id }) }); const data = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setNotice(data.error ?? "无法删除知识库。"); return; } setOpen(false); await load(); onChange?.(); };
  return <><div className="knowledge-base-manager"><Button type="button" variant="secondary" onClick={() => edit()}><Plus size={16}/> 新建知识库</Button><details><summary><Database size={16}/> 管理知识库</summary><div>{bases.map((base) => <button type="button" key={base.id} onClick={() => edit(base)}><span><strong>{base.name}</strong><small>{base.description || "没有说明"}</small></span><b>{base.cardCount}</b></button>)}<Button type="button" variant="ghost" onClick={() => setImportOpen(true)}><FileUp size={16}/> 导入知识库分享文件</Button></div></details></div>{notice && <div className="notice" role="status">{notice}</div>}
    {open && <div className="entity-manager-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="entity-manager" role="dialog" aria-modal="true" aria-labelledby="kb-manager-title"><header><div><p className="eyebrow"><Database size={15}/> 知识库</p><h2 id="kb-manager-title">{editing ? "编辑知识库" : "建立知识库"}</h2></div><button type="button" className="icon-close" onClick={() => setOpen(false)}><X size={19}/></button></header><form className="form-grid" onSubmit={save}><label className="field">名称<input value={name} onChange={(event) => setName(event.target.value)} required maxLength={120}/></label><label className="field">说明<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={4} maxLength={2000}/></label><footer><div>{editing && <><a className="button ghost" href={`/api/sharing?type=knowledge-base&id=${editing.id}`} download><Download size={16}/> 分享文件</a><Button type="button" variant="danger" disabled={editing.cardCount > 0} title={editing.cardCount ? "请先移动或删除库内卡片" : "删除知识库"} onClick={remove}><Trash2 size={16}/> 删除</Button></>}</div><div><Button type="button" variant="ghost" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={busy || !name.trim()}>{busy ? "保存中…" : "保存知识库"}</Button></div></footer></form></section></div>}
    <ShareImportDialog open={importOpen} expectedType="knowledge-base" onClose={() => setImportOpen(false)} onImported={(message) => { setNotice(message); void load(); onChange?.(); }}/>
  </>;
}
