"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Download, FileUp, PencilRuler, Plus, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui";
import { ShareImportDialog } from "@/components/share-import-dialog";
import type { KnowledgeBase, StudyPlan } from "@/lib/types";

export function StudyPlanManager({ onReadyChange }: { onReadyChange?: (ready: boolean) => void }) {
  const [plans, setPlans] = useState<StudyPlan[]>([]); const [bases, setBases] = useState<KnowledgeBase[]>([]); const [activeId, setActiveId] = useState("");
  const [open, setOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [planResponse, baseResponse] = await Promise.all([fetch("/api/study-plans", { cache: "no-store" }), fetch("/api/knowledge-bases", { cache: "no-store" })]); const planData = await planResponse.json() as { plans: StudyPlan[]; activePlanId: string | null }; const baseData = await baseResponse.json() as { knowledgeBases: KnowledgeBase[] }; setPlans(planData.plans); setBases(baseData.knowledgeBases); setActiveId(planData.activePlanId ?? ""); const active = planData.plans.find((plan) => plan.id === planData.activePlanId); onReadyChange?.(Boolean(active?.knowledgeBaseIds.length)); }, [onReadyChange]);
  useEffect(() => { void load(); }, [load]);
  const active = plans.find((plan) => plan.id === activeId);
  const activate = async (id: string) => { setBusy(true); await fetch("/api/study-plans", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "activate", id }) }); setBusy(false); window.location.reload(); };
  const edit = (plan?: StudyPlan) => { setEditingId(plan?.id ?? null); setName(plan?.name ?? ""); setDescription(plan?.description ?? ""); setSelected(plan?.knowledgeBaseIds ?? []); setOpen(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); const response = await fetch("/api/study-plans", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...(editingId ? { id: editingId } : {}), name, description, knowledgeBaseIds: selected }) }); const data = await response.json() as { error?: string }; setBusy(false); if (!response.ok) { setNotice(data.error ?? "无法保存计划书。"); return; } setOpen(false); setNotice("计划书已保存。"); await load(); };
  const remove = async () => { if (!editingId || !window.confirm("删除计划书？知识库和卡片不会被删除。")) return; setBusy(true); const response = await fetch("/api/study-plans", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId }) }); setBusy(false); if (response.ok) { setOpen(false); await load(); } };
  return <><section className="active-plan-bar" aria-label="当前计划书"><div><p className="eyebrow"><PencilRuler size={15}/> 当前计划书</p><select value={activeId} disabled={busy || !plans.length} onChange={(event) => void activate(event.target.value)} aria-label="选择当前计划书">{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><span>{active ? `${active.knowledgeBaseIds.length} 个知识库 · ${active.knowledgeBases.reduce((sum, base) => sum + base.cardCount, 0)} 张卡片` : "尚未选择计划书"}</span></div><div><Button type="button" variant="secondary" onClick={() => edit(active)} disabled={!active}>管理当前计划</Button><Button type="button" variant="ghost" onClick={() => edit()}><Plus size={16}/> 新建</Button><Button type="button" variant="ghost" onClick={() => setImportOpen(true)}><FileUp size={16}/> 导入</Button></div></section>{active && !active.knowledgeBaseIds.length && <div className="notice plan-empty-notice">当前计划书还没有知识库。添加知识库后才能开始学习和练习。</div>}{notice && <div className="notice" role="status">{notice}</div>}
    {open && <div className="entity-manager-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="entity-manager" role="dialog" aria-modal="true" aria-labelledby="plan-manager-title"><header><div><p className="eyebrow">计划书</p><h2 id="plan-manager-title">{editingId ? "整理学习范围" : "新建一份计划书"}</h2></div><button type="button" className="icon-close" onClick={() => setOpen(false)}><X size={19}/></button></header><form onSubmit={save} className="form-grid"><label className="field">名称<input value={name} onChange={(event) => setName(event.target.value)} required maxLength={120}/></label><label className="field">说明<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={3} maxLength={2000}/></label><fieldset className="entity-choice-list"><legend>关联知识库</legend>{bases.map((base) => <label key={base.id}><input type="checkbox" checked={selected.includes(base.id)} onChange={(event) => setSelected((items) => event.target.checked ? [...items, base.id] : items.filter((id) => id !== base.id))}/><span><strong>{base.name}</strong><small>{base.cardCount} 张卡片</small></span></label>)}</fieldset><footer><div>{editingId && <><a className="button ghost" href={`/api/sharing?type=study-plan&id=${editingId}`} download><Download size={16}/> 分享文件</a><Button type="button" variant="danger" onClick={remove}><Trash2 size={16}/> 删除</Button></>}</div><div><Button type="button" variant="ghost" onClick={() => setOpen(false)}>取消</Button><Button type="submit" disabled={busy || !name.trim()}>{busy ? "保存中…" : "保存计划书"}</Button></div></footer></form></section></div>}
    <ShareImportDialog open={importOpen} expectedType="study-plan" onClose={() => setImportOpen(false)} onImported={(message) => { setNotice(message); void load(); }}/>
  </>;
}
