"use client";

import { FormEvent, useMemo, useState } from "react";
import { CheckCircle2, Plus, Search, Tag, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui";
import type { Tag as TagItem, TagDisplayLanguage } from "@/lib/types";
import { formatTag } from "@/lib/tags-client";

export function TagManagerDialog({ tags, language, onClose, onChange }: { tags: TagItem[]; language: TagDisplayLanguage; onClose: () => void; onChange: () => Promise<void> }) {
  const [query, setQuery] = useState(""); const [editing, setEditing] = useState<TagItem | null>(null); const [zh, setZh] = useState(""); const [en, setEn] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const visible = useMemo(() => tags.filter((tag) => `${tag.chinese} ${tag.english}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [tags, query]);
  const begin = (tag?: TagItem) => { setEditing(tag ?? { id: "", key: "", chinese: "", english: "" }); setZh(tag?.chinese ?? ""); setEn(tag?.english ?? ""); setError(""); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; setBusy(true); setError(""); try { const response = await fetch(editing.id ? `/api/tags/${editing.id}` : "/api/tags", { method: editing.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chinese: zh, english: en }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setEditing(null); await onChange(); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法保存标签。"); } finally { setBusy(false); } };
  const remove = async (tag: TagItem) => { if (!window.confirm(`确认删除“${formatTag(tag, language)}”吗？它会从所有已使用的卡片中移除。`)) return; setBusy(true); try { const response = await fetch(`/api/tags/${tag.id}`, { method: "DELETE" }); if (!response.ok) throw new Error("无法删除标签。"); await onChange(); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法删除标签。"); } finally { setBusy(false); } };
  return <div className="tag-manager-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="tag-manager-dialog" role="dialog" aria-modal="true" aria-labelledby="tag-manager-title"><button className="icon-close" type="button" onClick={onClose} aria-label="关闭标签管理"><X size={19}/></button><header><p className="eyebrow"><Tag size={15}/> 标签管理</p><h2 id="tag-manager-title">让每个标签，双语清晰。</h2><p>编辑会立即同步到所有关联卡片。</p></header><div className="tag-manager-tools"><label className="tag-manager-search"><Search size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索中文或英文" /></label><Button type="button" onClick={() => begin()}><Plus size={16}/> 新建标签</Button></div>{error && <p className="danger" role="alert">{error}</p>}{editing ? <form className="tag-edit-form" onSubmit={save}><strong>{editing.id ? "编辑标签" : "新建标签"}</strong><div className="form-grid two"><label className="field">中文<input autoFocus value={zh} onChange={(event) => setZh(event.target.value)} placeholder="例如：检索增强生成" /></label><label className="field">English<input value={en} onChange={(event) => setEn(event.target.value)} placeholder="e.g. Retrieval-Augmented Generation" /></label></div><p className="field-help">至少填写一项；缺失语言会自动回退显示已填写内容。</p><div className="form-actions"><Button type="button" variant="ghost" onClick={() => setEditing(null)} disabled={busy}>取消</Button><Button type="submit" disabled={busy}>{busy ? "正在保存…" : <><CheckCircle2 size={16}/> 保存标签</>}</Button></div></form> : <div className="tag-manager-list">{visible.length ? visible.map((tag) => <article key={tag.id}><div><strong>{formatTag(tag, language)}</strong><small>中文：{tag.chinese || "—"}　English：{tag.english || "—"}</small></div><span>{tag.usageCount ?? 0} 张卡片</span><Button type="button" variant="ghost" onClick={() => begin(tag)}>编辑</Button><Button type="button" variant="ghost" className="tag-delete-action" disabled={busy} onClick={() => void remove(tag)} aria-label={`删除 ${formatTag(tag, language)}`}><Trash2 size={16}/></Button></article>) : <p className="muted-copy">还没有匹配的标签。</p>}</div>}</section></div>;
}
