#!/usr/bin/env bash
set -euo pipefail

# Study Desk WebDAV deployment and account manager. Run this script once to
# deploy, then use `sudo study-desk-webdav` to manage isolated sync accounts.

INSTALL_DIR="${STUDY_DESK_WEBDAV_INSTALL_DIR:-/opt/study-desk-webdav}"
ACCOUNTS_DIR="${INSTALL_DIR}/accounts"
DATA_DIR="${INSTALL_DIR}/data"
DEFAULT_REMOTE_DIRECTORY="study-desk"
SCRIPT_URL="https://raw.githubusercontent.com/JikoSchnee/Study-Desk/main/scripts/setup-webdav.sh"

say() { printf '%s\n' "$*"; }
die() { say "$*" >&2; exit 1; }

require_root() {
  [[ "${EUID}" -eq 0 ]] || die "请使用 sudo 运行此命令。"
}

require_tty() {
  [[ -r /dev/tty ]] || die "需要可交互终端。请先下载脚本，再用 sudo bash setup-webdav.sh 执行。"
}

require_docker() {
  command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1 \
    || die "需要先安装 Docker Engine 与 Docker Compose 插件，然后重新运行此脚本。"
}

read_tty() { IFS= read -r "$1" < /dev/tty; }

valid_username() {
  [[ "$1" =~ ^[A-Za-z0-9_-]{1,64}$ ]]
}

account_file() { printf '%s/%s.conf' "${ACCOUNTS_DIR}" "$1"; }
account_data_dir() { printf '%s/users/%s' "${DATA_DIR}" "$1"; }

encode_password() { printf '%s' "$1" | base64 | tr -d '\n'; }
decode_password() { printf '%s' "$1" | base64 -d; }

yaml_quote() {
  local value="$1"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '"%s"' "$value"
}

new_password() { openssl rand -hex 24; }

prompt_password() {
  local choice password confirm
  while true; do
    read -r -p "自动生成高强度密码？[Y/n] " choice < /dev/tty
    if [[ "${choice,,}" != "n" ]]; then
      new_password
      return
    fi
    read -r -s -p "请输入密码（至少 12 个字符）: " password < /dev/tty
    printf '\n'
    read -r -s -p "请再次输入密码: " confirm < /dev/tty
    printf '\n'
    [[ "${#password}" -ge 12 ]] || { say "密码至少需要 12 个字符。"; continue; }
    [[ "$password" != *$'\n'* && "$password" != *$'\r'* ]] || { say "密码不能包含换行符。"; continue; }
    [[ "$password" == "$confirm" ]] || { say "两次输入的密码不一致。"; continue; }
    printf '%s' "$password"
    return
  done
}

write_account() {
  local username="$1" password="$2" enabled="$3" created_at="${4:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"
  install -d -m 0700 "${ACCOUNTS_DIR}" "$(account_data_dir "${username}")"
  umask 077
  {
    printf 'username=%s\n' "$username"
    printf 'password_b64=%s\n' "$(encode_password "$password")"
    printf 'enabled=%s\n' "$enabled"
    printf 'created_at=%s\n' "$created_at"
  } > "$(account_file "${username}")"
  chmod 0600 "$(account_file "${username}")"
}

load_account() {
  local username="$1" file
  file="$(account_file "${username}")"
  [[ -f "$file" ]] || return 1
  # Account files are generated by this root-only script and contain only fixed keys.
  # shellcheck disable=SC1090
  source "$file"
  ACCOUNT_USERNAME="$username"
  ACCOUNT_PASSWORD="$(decode_password "$password_b64")"
  ACCOUNT_ENABLED="$enabled"
  ACCOUNT_CREATED_AT="$created_at"
}

regenerate_config() {
  local file username password
  umask 077
  {
    cat <<'EOF'
address: 0.0.0.0
port: 6065
behindProxy: true
directory: /data/empty
permissions: CRUD
# Kept for compatibility with older hacdias/webdav images.
modify: true
users:
EOF
    shopt -s nullglob
    for file in "${ACCOUNTS_DIR}"/*.conf; do
      username="$(basename "$file" .conf)"
      load_account "$username"
      [[ "$ACCOUNT_ENABLED" == "true" ]] || continue
      password="$(yaml_quote "$ACCOUNT_PASSWORD")"
      cat <<EOF
  - username: "${ACCOUNT_USERNAME}"
    password: ${password}
    directory: "/data/users/${ACCOUNT_USERNAME}"
    permissions: CRUD
    modify: true
EOF
    done
  } > "${INSTALL_DIR}/config.yml"
  chmod 0600 "${INSTALL_DIR}/config.yml"
}

restart_webdav() {
  (cd "${INSTALL_DIR}" && docker compose up -d --force-recreate webdav)
}

print_client_settings() {
  local username="$1" password="$2" domain
  domain="$(awk -F= '$1 == "DOMAIN" {print substr($0, index($0, "=") + 1); exit}' "${INSTALL_DIR}/.env")"
  cat <<EOF

请在 Study Desk 的“设置 → 备份与云同步”填写：

  WebDAV 地址: https://${domain}
  远端目录: ${DEFAULT_REMOTE_DIRECTORY}
  用户名: ${username}
  WebDAV 密码: ${password}

同一账号的其他设备使用完全相同的四项内容，即可接入同一云端。
EOF
}

create_account() {
  local username="$1" password="$2"
  valid_username "$username" || die "用户名只能包含字母、数字、下划线和连字符，且长度不超过 64。"
  [[ ! -e "$(account_file "$username")" ]] || die "账号 ${username} 已存在。"
  write_account "$username" "$password" true
  regenerate_config
  restart_webdav
}

reset_account_password() {
  local username="$1" password="$2"
  load_account "$username" || die "账号不存在。"
  write_account "$username" "$password" "$ACCOUNT_ENABLED" "$ACCOUNT_CREATED_AT"
  regenerate_config
  restart_webdav
}

set_account_enabled() {
  local username="$1" desired="$2"
  [[ "$desired" == "true" || "$desired" == "false" ]] || die "账号状态无效。"
  load_account "$username" || die "账号不存在。"
  [[ "$desired" == "true" ]] && install -d -m 0700 "$(account_data_dir "$username")"
  write_account "$username" "$ACCOUNT_PASSWORD" "$desired" "$ACCOUNT_CREATED_AT"
  regenerate_config
  restart_webdav
}

purge_account_data() {
  local username="$1" target
  load_account "$username" || die "账号不存在。"
  [[ "$ACCOUNT_ENABLED" == "false" ]] || die "请先禁用该账号，再永久删除数据。"
  target="$(account_data_dir "$username")"
  [[ "$target" == "${DATA_DIR}/users/${username}" && -d "$target" ]] || die "数据目录校验失败，已中止。"
  rm -rf -- "$target"
}

migrate_legacy_installation() {
  [[ -d "${INSTALL_DIR}" && ! -d "${ACCOUNTS_DIR}" ]] || return
  local username password legacy_env target entry
  legacy_env="${INSTALL_DIR}/.env"
  [[ -f "$legacy_env" ]] || die "检测到旧部署，但缺少 ${legacy_env}，无法安全迁移。"
  username="$(awk -F= '$1 == "WEBDAV_USERNAME" {print substr($0, index($0, "=") + 1); exit}' "$legacy_env")"
  password="$(awk -F= '$1 == "WEBDAV_PASSWORD" {print substr($0, index($0, "=") + 1); exit}' "$legacy_env")"
  valid_username "$username" || die "旧部署的用户名无法识别，请先备份 ${INSTALL_DIR} 后手动处理。"
  [[ -n "$password" ]] || die "旧部署密码无法识别，请先备份 ${INSTALL_DIR} 后手动处理。"

  say "检测到旧版单账号部署，正在迁移 ${username} 的同步数据到独立空间…"
  (cd "${INSTALL_DIR}" && docker compose stop webdav)
  target="$(account_data_dir "$username")"
  install -d -m 0700 "$target"
  shopt -s dotglob nullglob
  for entry in "${DATA_DIR}"/*; do
    [[ "$(basename "$entry")" == "users" ]] && continue
    mv "$entry" "$target/"
  done
  shopt -u dotglob
  write_account "$username" "$password" true
  regenerate_config
  restart_webdav
  say "旧账号 ${username} 已迁移完成。"
}

install_manager_command() {
  local self_path="${BASH_SOURCE[0]}" temporary_path="${INSTALL_DIR}/manage.sh.download"
  if [[ -f "$self_path" ]]; then
    if [[ ! -f "${INSTALL_DIR}/manage.sh" || ! "$self_path" -ef "${INSTALL_DIR}/manage.sh" ]]; then
      install -m 0700 "$self_path" "${INSTALL_DIR}/manage.sh"
    fi
  else
    command -v curl >/dev/null 2>&1 || die "通过管道部署时需要 curl 以安装账号管理命令。"
    curl -fsSL "$SCRIPT_URL" -o "$temporary_path" || die "无法下载账号管理脚本，请改为先下载脚本后执行。"
    install -m 0700 "$temporary_path" "${INSTALL_DIR}/manage.sh"
    rm -f "$temporary_path"
  fi
  ln -sfn "${INSTALL_DIR}/manage.sh" /usr/local/bin/study-desk-webdav
}

list_accounts() {
  local file username status size
  say ""
  printf '%-20s %-10s %-22s %s\n' "用户名" "状态" "创建时间" "空间占用"
  shopt -s nullglob
  for file in "${ACCOUNTS_DIR}"/*.conf; do
    username="$(basename "$file" .conf)"
    load_account "$username"
    status="已启用"; [[ "$ACCOUNT_ENABLED" == "true" ]] || status="已禁用"
    size="$(du -sh "$(account_data_dir "$username")" 2>/dev/null | awk '{print $1}')"
    printf '%-20s %-10s %-22s %s\n' "$username" "$status" "$ACCOUNT_CREATED_AT" "${size:-0}"
  done
}

prompt_username() {
  local username
  read -r -p "用户名（字母、数字、_、-）: " username < /dev/tty
  valid_username "$username" || { say "用户名格式无效。"; return 1; }
  printf '%s' "$username"
}

manage_create() {
  local username password
  username="$(prompt_username)" || return
  [[ ! -f "$(account_file "$username")" ]] || { say "账号已存在。"; return; }
  password="$(prompt_password)"
  create_account "$username" "$password"
  say "账号 ${username} 已创建并启用。"
  print_client_settings "$username" "$password"
}

manage_reset_password() {
  local username password
  username="$(prompt_username)" || return
  load_account "$username" || { say "账号不存在。"; return; }
  password="$(prompt_password)"
  reset_account_password "$username" "$password"
  say "密码已重置。"
  print_client_settings "$username" "$password"
}

manage_set_enabled() {
  local desired="$1" username label
  username="$(prompt_username)" || return
  set_account_enabled "$username" "$desired" || { say "账号不存在。"; return; }
  label="禁用"; [[ "$desired" == "true" ]] && label="启用"
  say "账号 ${username} 已${label}。"
}

manage_purge_data() {
  local username confirmation target
  username="$(prompt_username)" || return
  load_account "$username" || { say "账号不存在。"; return; }
  [[ "$ACCOUNT_ENABLED" == "true" ]] && { say "请先禁用该账号，再永久删除数据。"; return; }
  read -r -p "这会永久删除 ${username} 的全部云端快照。请输入用户名确认: " confirmation < /dev/tty
  [[ "$confirmation" == "$username" ]] || { say "未确认，未删除任何数据。"; return; }
  purge_account_data "$username"
  say "已永久删除 ${username} 的云端数据；账号记录仍保留，可重新启用后使用空空间。"
}

manager_menu() {
  local choice
  while true; do
    cat <<'EOF'

Study Desk WebDAV 账号管理
  1) 创建账号
  2) 查看账号与空间占用
  3) 重置账号密码
  4) 禁用账号（保留数据）
  5) 启用账号
  6) 永久删除已禁用账号的数据
  0) 退出
EOF
    read -r -p "请选择操作: " choice < /dev/tty
    case "$choice" in
      1) manage_create ;;
      2) list_accounts ;;
      3) manage_reset_password ;;
      4) manage_set_enabled false ;;
      5) manage_set_enabled true ;;
      6) manage_purge_data ;;
      0) return ;;
      *) say "请输入 0 到 6。" ;;
    esac
  done
}

initial_deploy() {
  local domain username password
  read -r -p "请输入已解析到此服务器的域名（例如 sync.example.com）: " domain < /dev/tty
  [[ "$domain" =~ ^[A-Za-z0-9.-]+$ && "$domain" == *.* ]] || die "域名格式无效。请先将域名 A/AAAA 记录指向此服务器。"
  while true; do
    username="$(prompt_username)" || continue
    break
  done
  password="$(prompt_password)"

  install -d -m 0700 "$INSTALL_DIR" "$DATA_DIR" "$ACCOUNTS_DIR" "${DATA_DIR}/empty"
  printf 'DOMAIN=%s\n' "$domain" > "${INSTALL_DIR}/.env"
  chmod 0600 "${INSTALL_DIR}/.env"
  cat > "${INSTALL_DIR}/Caddyfile" <<'EOF'
{$DOMAIN} {
  reverse_proxy webdav:6065
}
EOF
  cat > "${INSTALL_DIR}/compose.yml" <<'EOF'
services:
  webdav:
    image: hacdias/webdav:latest
    restart: unless-stopped
    command: -c /config.yml
    env_file: .env
    volumes:
      - ./config.yml:/config.yml:ro
      - ./data:/data
  caddy:
    image: caddy:2
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
EOF
  chmod 0600 "${INSTALL_DIR}/.env"
  install_manager_command
  create_account "$username" "$password"
  (cd "$INSTALL_DIR" && docker compose up -d caddy)
  say "部署完成。"
  print_client_settings "$username" "$password"
  say "以后运行 sudo study-desk-webdav 即可创建和管理更多账号。"
}

main() {
  require_root
  require_tty
  require_docker
  if [[ -d "$INSTALL_DIR" ]]; then
    migrate_legacy_installation
    install_manager_command
    manager_menu
  else
    initial_deploy
  fi
}

if [[ "${STUDY_DESK_WEBDAV_LIBRARY:-}" != "1" ]]; then
  main "$@"
fi
